### ISSUE TITLE
Runtime error during sync_deps.py 

### ISSUE THREAD

**Issue by VimalWill** [nod-ai/iree-amd-aie#226]
Hi, I encountered an RuntimeError while running the sync_deps.py script 

```
Errors during submodule fetch:
	third_party/llvm-project
Traceback (most recent call last):
  File "/home/vimal/Edge_ai/iree-amd-aie/sync_deps.py", line 123, in <module>
    main()
  File "/home/vimal/Edge_ai/iree-amd-aie/sync_deps.py", line 75, in main
    run(fetch_args, repo_dir)
  File "/home/vimal/Edge_ai/iree-amd-aie/sync_deps.py", line 117, in run
    raise RuntimeError(f"Git command failed: {args_text} (from {cwd})"
RuntimeError: Git command failed: git fetch origin 4691fc5bf37d6ba8aeac6a1c5382a595fa900f4c (from /home/vimal/Edge_ai/iree)
```

**Comment by nirvedhmeshram** [comment]
Hi,
I see you got ` RuntimeError: Git command failed: git fetch origin 4691fc5bf37d6ba8aeac6a1c5382a595fa900f4c (from /home/vimal/Edge_ai/iree)`
Does this path exist?
`/home/vimal/Edge_ai/iree`
As mentioned in README,
```
These instructions assume that you have an appropriate IREE checkout side by side with this repository have an IREE build setup in an iree-build directory that is also a sibling. This is not a requirement, but instructions will need to be changed for different paths.
```

**Comment by nirvedhmeshram** [comment]
Also, you may use this wiki page to get some minimal starting instructions about the dependencies
https://github.com/nod-ai/iree-amd-aie/wiki/Getting-Started

**Comment by VimalWill** [comment]
Thanks @nirvedhmeshram, problem resolved!
